inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.1
Gemspec/RequireMFA:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
